package com.example.unnati.ui.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.unnati.data.repository.UnnatiRepository
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import java.text.NumberFormat
import java.text.SimpleDateFormat
import java.util.*

class ExportViewModel(private val repository: UnnatiRepository) : ViewModel() {

    private val _report = MutableStateFlow("")
    val report: StateFlow<String> = _report

    private val currency = NumberFormat.getCurrencyInstance(Locale("en", "IN"))
    private val sdf = SimpleDateFormat("dd/MM/yyyy", Locale.getDefault())

    fun buildReport() = viewModelScope.launch {
        val members = repository.allActiveMembers.first()
        val capital = repository.totalGroupCapital.first() ?: 0.0
        val loans = repository.activeLoans.first()

        val sb = StringBuilder()
        sb.appendLine("Mahila-Shakti Unnati — Group Report")
        sb.appendLine("Date: ${sdf.format(Date())}")
        sb.appendLine("─".repeat(36))
        sb.appendLine("Total Members:   ${members.size}")
        sb.appendLine("Group Capital:   ${currency.format(capital)}")
        sb.appendLine()
        sb.appendLine("Active Loans:    ${loans.size}")
        sb.appendLine("Outstanding:     ${currency.format(loans.sumOf { it.principal })}")
        sb.appendLine("─".repeat(36))
        sb.appendLine("Members:")
        members.forEach { m ->
            val savings = repository.getTotalSavingsForMember(m.id).first() ?: 0.0
            sb.appendLine("  ${m.name.padEnd(20)} ${currency.format(savings)}")
        }
        sb.appendLine("─".repeat(36))
        sb.appendLine("Generated by Mahila-Shakti Unnati v1.0")
        _report.value = sb.toString()
    }
}
